### ISSUE TITLE
已经把脚本下载下来了，根据提示无法找到关键词，脚本要如何使用？

### ISSUE THREAD

**Issue by katfionn** [leafTheFish/DeathNote#109]
## 问题

我是想用美团V3的，看到了如下提示
```
meituanCookie
```
但我在全文代码里找不到这个关键词，不知道哪里填写这个东西的值；青龙有个变量管理，但是建立变量的时候又没有说这个变量适用于哪个脚本的

## 已尝试

- 直接把这一段（填了真实饼干的）塞在代码末尾或开头，运行直接报错
-     ![image](https://github.com/leafTheFish/DeathNote/assets/136874302/f8c2e5ca-2078-44f3-a529-c6631ec8d664)
- 直接上面一段直接塞在青龙一个叫环境变量菜单下config.sh文件的末尾
-     运行直接报错
![image](https://github.com/leafTheFish/DeathNote/assets/136874302/22ffd85e-05e9-42df-80e9-a389bc672870)

## 环境
青龙

## 其他说明

纯小白，没有加密解密、逆向基础

**Comment by OldCoding** [comment]
![image](https://github.com/leafTheFish/DeathNote/assets/85047508/e14f0501-ca81-47d5-9817-c84bf5dd5eca)
就在hrj环境变量里面填写就行

**Comment by katfionn** [comment]
> ![image](https://private-user-images.githubusercontent.com/85047508/311477978-e14f0501-ca81-47d5-9817-c84bf5dd5eca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTc1NTcsIm5iZiI6MTcxMDA1NzI1NywicGF0aCI6Ii84NTA0NzUwOC8zMTE0Nzc5NzgtZTE0ZjA1MDEtY2E4MS00N2Q1LTk4MTctYzg0YmY1ZGQ1ZWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDA3NTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNTQ4NmU0ZjQyOWU3YWNiNjVhYTM1NmQxODhlMmQxOThhMjE4NjIyYWQ1NmM0ZWJlZTExNDcxNzYxNTg0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3h_9dsBM9LG8Z8Hg3T6XdF4anGTrAPdRs7RBABmzTdY) 就在hrj环境变量里面填写就行

好，非常感谢大佬
