### ISSUE TITLE
elmV3.js失效

### ISSUE THREAD

**Issue by google-mirror** [leafTheFish/DeathNote#33]
刷新CK报错

**Comment by google-mirror** [comment]
依然不行

**Comment by taichao1** [comment]
我是提示风控用户。。而且饿了么豆的任务删除了，那怎么获豆呢。。

**Comment by google-mirror** [comment]
> 我是提示风控用户。。而且饿了么豆的任务删除了，那怎么获豆呢。。

我是登陆都登陆不了, cookie参数不匹配

**Comment by zlhdd108** [comment]
任务跑到一半就提示“任务[3528001:45:PAGEVIEW]完成出错: FAIL_SYS_SESSION_EXPIRED::Session过期”，然后就是CK过期了……
