### ISSUE TITLE
别克汇app羊毛不错

### ISSUE THREAD

**Issue by jaychoubaby** [leafTheFish/DeathNote#55]
![image](https://github.com/leafTheFish/DeathNote/assets/26641387/466a1291-6a57-426e-ac40-958dc1af3af2)![image](https://github.com/leafTheFish/DeathNote/assets/26641387/600103c7-3cc5-4466-9448-d1ed8ee8543e)![image](https://github.com/leafTheFish/DeathNote/assets/26641387/56bb5f39-e739-455b-93f7-e59a713c834c)

如题，别克汇app 应用名：ibuick，有赚积分任务，任务种类很多获取积分容易，积分可以抵扣现金在app内的商城进行购物，商城内商品种类很多质量也不错，自己手动抓包研究过一段时间但是无果，希望大佬可以发挥一下

**Comment by 745240** [comment]
ck有效半小时，我写了也要每天抓包，每天手动运行

**Comment by jaychoubaby** [comment]
> ck有效半小时，我写了也要每天抓包，每天手动运行

每天抓包倒也还好，就是做任务有点繁琐，求个脚本啊大佬

**Comment by jaychoubaby** [comment]
> ck有效半小时，我写了也要每天抓包，每天手动运行

我测试试试 感谢
